#!/bin/bash
# GCP IAM Policy Vulnerability Scanner
# Usage: gcp_iam_vuln_scan.sh <project_id>

PROJECT_ID=$1

if [ -z "$PROJECT_ID" ]; then
    echo "Usage: $0 <project_id>"
    exit 1
fi

echo "Starting GCP IAM Policy Vulnerability Scan..."

# Ensure Forseti Security is installed
if ! command -v forseti &> /dev/null; then
    echo "Forseti Security could not be found, please install it first."
    exit 1
fi

# Initialize Forseti Security
forseti model create --source=inventory --project_id=$PROJECT_ID
forseti inventory create

# Run Forseti scanner
forseti scanner run

# Generate a report
forseti notifier run

echo "GCP IAM Policy Vulnerability Scan completed. Report generated by Forseti Security."
